### ISSUE TITLE
environment.yml

### ISSUE THREAD

**Issue by KimRoos** [PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading-sample#1]
Can't find the environment.yml file mentioned on page 15 in the book.

**Comment by rhemac-git** [comment]
Hi Kim,

I found another yml under here:

[https://github.com/PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading/tree/master/Chapter09](url)

Guess the book is still very new and we may need to wait a while for everything to get done.  For example, the PDF for later chapters on Deep Learning, is not accessible yet....

I am so excited to see what will I learn from this book.  :)

**Comment by sayli2212** [comment]
Hi Kim,

The required environment.yml has been uploaded on the repo.
